services:
  db:
    image: postgres:16
    container_name: workout_sheet_v2_db
    environment:
      POSTGRES_DB: workout_sheet_api_v2
      POSTGRES_USER: workout_sheet_api
      POSTGRES_PASSWORD: workout_sheet_api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U workout_sheet_api -d workout_sheet_api_v2']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_v2:
